name: firebase_examples
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 1.17.1
  firebase_auth: 3.3.19
  modal_progress_hud_nsn: 0.2.1
  google_sign_in: 5.3.3
  cloud_firestore: 3.1.18
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

